In [1]:
import numpy as np

# Datatypes and Attributes 

In [3]:
a1 = np.array([26,12,3])

In [5]:
print(type(a1))
a1

<class 'numpy.ndarray'>


array([26, 12,  3])

In [17]:
a2 = np.array([[1,'ML',3],[4,5,6]])
a2

array([['1', 'ML', '3'],
       ['4', '5', '6']], dtype='<U11')

In [20]:
a3 = np.array([[[1,2,3],[4,5,6.8]],[[7,8,9],[9,10,11]]])
a3


array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6.8]],

       [[ 7. ,  8. ,  9. ],
        [ 9. , 10. , 11. ]]])

In [21]:
a1.shape,a2.shape,a3.shape # diffrent layers on each axis

((3,), (2, 3), (2, 2, 3))

In [10]:
a1.size,a2.size,a3.size #no. of elements

(3, 6, 12)

In [22]:
print(a3.dtype) #float if any one of the values is float
a2.dtype

float64


dtype('<U11')

In [24]:
import pandas as pd
df = pd.DataFrame(a2)
df #represents lists in proper format

0   1  2
0  1  ML  3
1  4   5  6

Creating arrays :


Place Holder array used for defining shape  :

In [29]:
ones = np.ones((7,8)) 
print(ones)
print(ones.dtype) #FLOAT
print(ones.shape)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
float64
(7, 8)


In [32]:
zero = np.zeros((7,8)) 
print(zero)
print(zero.dtype) #FLOAT
print(zero.shape)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
float64
(7, 8)


In [35]:
range_arr = np.arange(0,100,5) #start stop step
range_arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [64]:
random_arr = np.random.randint(0,5,(5,2,3)) #randomly selects a number ...start,n+1,(size) 
#if 0,1 then array with zero numbers and when 1,2 array with all ones......
print(random_arr)
print(random_arr.dtype) #integer


[[[4 0 4]
  [0 3 2]]

 [[3 4 4]
  [0 0 0]]

 [[3 0 2]
  [0 1 4]]

 [[1 3 3]
  [0 3 0]]

 [[1 0 0]
  [4 4 4]]]
int32


In [61]:
np.random.seed(7) #seed set to constant  for this cell
random_arr2 = np.random.rand(5,2,3) #no tuples ie no limits only shape constraint
print(random_arr2)
print(random_arr2.dtype)#FLOAT

[[[0.07630829 0.77991879 0.43840923]
  [0.72346518 0.97798951 0.53849587]]

 [[0.50112046 0.07205113 0.26843898]
  [0.4998825  0.67923    0.80373904]]

 [[0.38094113 0.06593635 0.2881456 ]
  [0.90959353 0.21338535 0.45212396]]

 [[0.93120602 0.02489923 0.60054892]
  [0.9501295  0.23030288 0.54848992]]

 [[0.90912837 0.13316945 0.52341258]
  [0.75040986 0.66901324 0.46775286]]]
float64


In [63]:
np.random.seed(7) #seed same thus give same sequence of pseduo random numbers
random_arr3 = np.random.random((5,2)) #tuples considered ie no limits only shape constraint
print(random_arr3)
print(random_arr3.dtype)#FLOAT

[[0.07630829 0.77991879]
 [0.43840923 0.72346518]
 [0.97798951 0.53849587]
 [0.50112046 0.07205113]
 [0.26843898 0.4998825 ]]
float64


## Viewing Array

In [65]:
np.unique(random_arr) #all unique elements

array([0, 1, 2, 3, 4])

In [66]:
random_arr

array([[[4, 0, 4],
        [0, 3, 2]],

       [[3, 4, 4],
        [0, 0, 0]],

       [[3, 0, 2],
        [0, 1, 4]],

       [[1, 3, 3],
        [0, 3, 0]],

       [[1, 0, 0],
        [4, 4, 4]]])

In [68]:
print('a1 = ',a1,'\n a2 = ',a2 ,'\n a3 = ',a3)

a1 =  [26 12  3] 
 a2 =  [['1' 'ML' '3']
 ['4' '5' '6']] 
 a3 =  [[[ 1.   2.   3. ]
  [ 4.   5.   6.8]]

 [[ 7.   8.   9. ]
  [ 9.  10.  11. ]]]


In [75]:
print(a1[0],a2[0],a3[0])

26 ['1' 'ML' '3'] [[1.  2.  3. ]
 [4.  5.  6.8]]


In [74]:
a2[0][2]

'3'

In [73]:
a3[0][0][2]

3.0

In [76]:
random_arr[:2,:2,:2]

array([[[4, 0],
        [0, 3]],

       [[3, 4],
        [0, 0]]])