In [19]:
import numpy as np

In [20]:
a1 = np.random.randint(0,10,(3,1))

In [21]:
a1

array([[8],
       [4],
       [2]])

In [22]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

Elements are added only when both the list have same size

In [23]:
a1+ones #all elements added in same position 
#np.add(a1,ones) #method

array([[9., 9., 9., 9., 9.],
       [5., 5., 5., 5., 5.],
       [3., 3., 3., 3., 3.]])

In [24]:
a1-ones

array([[7., 7., 7., 7., 7.],
       [3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1.]])

In [25]:
a1*ones

array([[8., 8., 8., 8., 8.],
       [4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2.]])

In [26]:
a2 = np.random.randint(90,100,(3,3))

In [27]:
a2

array([[90, 95, 94],
       [96, 92, 98],
       [98, 99, 91]])

In [28]:
a1*a2 # atleast one of them should match else

array([[720, 760, 752],
       [384, 368, 392],
       [196, 198, 182]])

In [29]:
X = np.arange(8).reshape(4, 2)
y = np.arange(2).reshape(1, 2)  # create a 1x2 matrix
X * y

array([[0, 1],
       [0, 3],
       [0, 5],
       [0, 7]])

In [30]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [31]:
y

array([[0, 1]])

a1[:, np.newaxis] adds a new axis to the 1D array, making it a column vector (shape: (3, 1)). The resulting shape is then compatible for broadcasting with the 2D array a2 (shape: (2, 3))

In [32]:
a1 = np.array([1, 2, 3])
a2 = np.array([[4, 5, 6],
               [7, 8, 9]])

In [33]:
# result = a1[:, np.newaxis] * a2 
a1*a2

array([[ 4, 10, 18],
       [ 7, 16, 27]])

In [34]:
a1/a2

array([[0.25      , 0.4       , 0.5       ],
       [0.14285714, 0.25      , 0.33333333]])

In [35]:
#Floor Division ie rounding to floor
a1//a2

array([[0, 0, 0],
       [0, 0, 0]])

In [36]:
a1**a2 #EXPONENTIAL

array([[    1,    32,   729],
       [    1,   256, 19683]])

In [37]:
print(np.exp(a1))
print(np.log(a1))

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


In [38]:
a1%2

array([1, 0, 1], dtype=int32)

## Aggregation


use sum(a) for python datatypes and np.sum(arr) for numpy arrays

In [39]:
np.sum(a2) #sum for numpy array

39

In [40]:
r = np.random.random(10000)# array of length 10000

In [41]:
r[0:10] #10 elements r[:10]

array([0.32086379, 0.91691832, 0.04704224, 0.79463461, 0.50547211,
       0.99245135, 0.69335643, 0.90607667, 0.06025345, 0.77266589])

Calculating time complexities of both methods

In [42]:
%timeit sum(r) #Python sum

2 ms ± 216 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [43]:
%timeit np.sum(r) #Numpy sum

12.3 µs ± 2.14 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


As we can see that the time taken by numpy method is lesser than python method which makes its use more efficient while handling numpy arrays

In [44]:
a2

array([[4, 5, 6],
       [7, 8, 9]])

In [45]:
print("mean : ",np.mean(a2))
print("Min : ",np.min(a2))
print("MAX : ",np.max(a2))
print("Standard Deviation : ",np.std(a2))
print("Variance : ",np.var(a2))


mean :  6.5
Min :  4
MAX :  9
Standard Deviation :  1.707825127659933
Variance :  2.9166666666666665


In [46]:
np.sqrt(np.var(a2)) #standard deviation

1.707825127659933

In [47]:
np.disp(a2) #returns list
np.percentile(a2,50)# 50th percentile

[[4 5 6]
 [7 8 9]]


6.5

In [48]:
high = np.array([100,500,800,1000,6000])
low = np.array([1,4,5,7,10])

In [49]:
np.var(high),np.var(low)# higher variance wider range of numbers 

(4757600.0, 9.040000000000001)

In [50]:
np.std(high),np.std(low)# average distance of a number from mean

(2181.192334481304, 3.006659275674582)

In [51]:
np.mean(high),np.mean(low)

(1680.0, 5.4)

# Reshaping and Transposing 

In [52]:
a2

array([[4, 5, 6],
       [7, 8, 9]])

In [53]:
a1

array([1, 2, 3])

In [56]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [69]:
# a2*a3 #value error
a4 = a2.reshape(2,3,1)# returns an array of diffrent shapes but has same data need to assign
#at least two dimensions must be same

In [70]:
a3.shape,a4.shape

((2, 3, 3), (2, 3, 1))

In [71]:
a4 *a3 #

array([[[  4,   8,  12],
        [ 20,  25,  30],
        [ 42,  48,  54]],

       [[ 70,  77,  84],
        [104, 112, 120],
        [144, 153, 162]]])

In [72]:
a3.T #transpose

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [74]:
#Dot product 
np.random.seed(0)
mat1 = np.random.randint(0,10,(5,3))
mat2 = np.random.randint(0,10,(5,3))

In [75]:
mat1,mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [76]:
mat1*mat2 # normal multiplication

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [77]:
np.dot(mat1,mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

# Comaprison Operators

In [78]:
a1,a2

(array([1, 2, 3]),
 array([[4, 5, 6],
        [7, 8, 9]]))

In [79]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [83]:
arr = a1>=a2
arr

array([[False, False, False],
       [False, False, False]])

In [85]:
arr.dtype,type(arr)

(dtype('bool'), numpy.ndarray)

In [86]:
a1<10

array([ True,  True,  True])

In [87]:
a1==a2

array([[False, False, False],
       [False, False, False]])

In [88]:
a2 == a1

array([[False, False, False],
       [False, False, False]])

In [97]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [102]:
np.sort(mat1)# sorts array elements in the lowest axis
# mat1.sort(axis=2) #modifies original matrix 
# mat1

array([[0, 3, 5],
       [1, 3, 5],
       [2, 6, 7],
       [3, 7, 8],
       [4, 8, 9]])

In [105]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [108]:
np.argsort(mat2) #sorts based on indexes and returns a new array
# mat2.argsort(axis=1)

array([[0, 1, 2],
       [1, 2, 0],
       [1, 0, 2],
       [2, 1, 0],
       [2, 0, 1]], dtype=int64)

In [109]:
np.argmax(mat2,axis=1)

array([1, 0, 0, 0, 1], dtype=int64)

In [110]:
np.argmax(mat2,axis=0)

array([2, 2, 2], dtype=int64)