In [78]:
import numpy as np

In [79]:
a1 = np.random.randint(0,10,(3,1))

In [80]:
a1

array([[0],
       [0],
       [0]])

In [81]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

Elements are added only when both the list have same size

In [82]:
a1+ones #all elements added in same position 
#np.add(a1,ones) #method

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [83]:
a1-ones

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])

In [84]:
a1*ones

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [85]:
a2 = np.random.randint(90,100,(3,3))

In [86]:
a2

array([[94, 97, 92],
       [95, 98, 96],
       [92, 91, 91]])

In [87]:
a1*a2 # atleast one of them should match else

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [88]:
X = np.arange(8).reshape(4, 2)
y = np.arange(2).reshape(1, 2)  # create a 1x2 matrix
X * y

array([[0, 1],
       [0, 3],
       [0, 5],
       [0, 7]])

In [89]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [90]:
y

array([[0, 1]])

a1[:, np.newaxis] adds a new axis to the 1D array, making it a column vector (shape: (3, 1)). The resulting shape is then compatible for broadcasting with the 2D array a2 (shape: (2, 3))

In [93]:
a1 = np.array([1, 2, 3])
a2 = np.array([[4, 5, 6],
               [7, 8, 9]])

In [94]:
result = a1[:, np.newaxis] * a2 

array([[ 4, 10, 18],
       [ 7, 16, 27]])

In [97]:
a1/a2

array([[0.25      , 0.4       , 0.5       ],
       [0.14285714, 0.25      , 0.33333333]])

In [98]:
#Floor Division ie rounding to floor
a1//a2

array([[0, 0, 0],
       [0, 0, 0]])

In [99]:
a1**a2 #EXPONENTIAL

array([[    1,    32,   729],
       [    1,   256, 19683]])

In [101]:
print(np.exp(a1))
print(np.log(a1))

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


In [102]:
a1%2

array([1, 0, 1], dtype=int32)