In [1]:
import numpy as np
import pandas as pd

In [5]:
#created a random weekly sales matrix
np.random.seed(0)
Week_sales = np.random.randint(20,size=(7,3))
Week_sales

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7],
       [14, 17,  5],
       [13,  8,  9]])

In [7]:
#creating Data frame
df = pd.DataFrame(Week_sales,index=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]
                  ,columns=["Milk","Tea","Sugar"])
df

Milk  Tea  Sugar
Sun    12   15      0
Mon     3    3      7
Tue     9   19     18
Wed     4    6     12
Thu     1    6      7
Fri    14   17      5
Sat    13    8      9

In [8]:
#Pricing of each product 
price = np.random.randint(100,size=(3))

In [9]:
price

array([20, 80, 69])

In [11]:
cost = pd.DataFrame(price,columns=["Rs."],index=["Milk","Tea","Sugar"])

In [12]:
cost

Rs.
Milk    20
Tea     80
Sugar   69

In [14]:
# to calculate total sales
reshaped = price.reshape(3,1)
reshaped

array([[20],
       [80],
       [69]])

In [17]:
total_sales = np.dot(Week_sales,reshaped)#(7,3)(3,1)=>(7,1)
total_sales

array([[1440],
       [ 783],
       [2942],
       [1388],
       [ 983],
       [1985],
       [1521]])

In [18]:
#adding total sales to data frame
df["Total Sales"]= total_sales

In [19]:
df

Milk  Tea  Sugar  Total Sales
Sun    12   15      0         1440
Mon     3    3      7          783
Tue     9   19     18         2942
Wed     4    6     12         1388
Thu     1    6      7          983
Fri    14   17      5         1985
Sat    13    8      9         1521